Add to the documentation a systemd service to restart the daemon
nextcloud/notify_push pull request #48
Opened 2021-02-26 23:41 UTC by trallen

... whenever the app is updated.

This suggestion uses a systemd .path file to monitor the daemon for changes. It has been tested and works correctly. (As far as I can tell, a systemd.path job will only start a service, not restart, so there needs to be a oneshot service that handles the actual restart.)

2021-03-03 14:29 UTC, icewind1991 commented
Thanks for your contribution, I'm hoping to do some restructuring of the README/docs soon™ I'll merge this in once that's done

2021-04-20 16:43 UTC, szaimen commented
Why not just adding those two values to the service?
```
Restart=on-failure
RestartSec=5s
```

2021-04-20 18:44 UTC, simonspa commented
> Why not just adding those two values to the service?
> 
> ```
> Restart=on-failure
> RestartSec=5s
> ```

Why would it fail? The service just keeps running even though the binary file has changed. So @trallen's solution seems to be more sound: we watch the binary path and restart the service once it changes.

2021-04-20 18:50 UTC, szaimen commented
> Why would it fail?

I thought the service would just fail if the binary gets changed/removed and not automatically restarted again?

2021-04-20 19:44 UTC, simonspa commented
> > Why would it fail?
> 
> I thought the service would just fail if the binary gets changed/removed and not automatically restarted again?

No, because the binary is loaded to RAM and executed. Once the service is started, it just happily keeps running no matter what you do with the original binary - you may even delete it. You need to actively stop it and restart with the new binary - which is what @trallen's path and service modules do.

2021-06-26 19:43 UTC, genofire requested changes

2021-06-26 19:43 UTC, genofire commented on README.md
> +
```suggestion
And enable it with:
```bash
systemctl enable --now notify_push-watcher.path
``` <- formatig error of github
```

---
You should something write, like my suggestion - to inform which of the systemd unit's should be started (.path or .service)

2021-08-04 12:59 UTC, icewind1991 commented
Thanks! I've merged the commit manually

2021-08-04 12:59 UTC, closed without merging